<?php

return [
    'full_list' => [
        'af' => 'waba.lang_codes.af', // 'Afrikaans',
        'sq' => 'waba.lang_codes.sq', // 'Albanian',
        'ar' => 'waba.lang_codes.ar', // 'Arabic',
        'ar_EG' => 'waba.lang_codes.ar_EG', // 'Arabic (Egypt)',
        'ar_AE' => 'waba.lang_codes.ar_AE', // 'Arabic (United Arab Emirates)',
        'ar_LB' => 'waba.lang_codes.ar_LB', // 'Arabic (Lebanon)',
        'ar_MA' => 'waba.lang_codes.ar_MA', // 'Arabic (Morocco)',
        'ar_QA' => 'waba.lang_codes.ar_QA', // 'Arabic (Qatar)',
        'az' => 'waba.lang_codes.az', // 'Azerbaijani',
        'be_BY' => 'waba.lang_codes.be_BY', // 'Belarusian',
        'bn' => 'waba.lang_codes.bn', // 'Bengali',
        'bn_IN' => 'waba.lang_codes.bn_IN', // 'Bengali (India)',
        'bg' => 'waba.lang_codes.bg', // 'Bulgarian',
        'ca' => 'waba.lang_codes.ca', // 'Catalan',
        'zh_CN' => 'waba.lang_codes.zh_CN', // 'Chinese (China)',
        'zh_HK' => 'waba.lang_codes.zh_HK', // 'Chinese (Hong Kong)',
        'zh_TW' => 'waba.lang_codes.zh_TW', // 'Chinese (Taiwan)',
        'hr' => 'waba.lang_codes.hr', // 'Croatian',
        'cs' => 'waba.lang_codes.cs', // 'Czech',
        'da' => 'waba.lang_codes.da', // 'Danish',
        'prs_AF' => 'waba.lang_codes.prs_AF', // 'Dari',
        'nl' => 'waba.lang_codes.nl', // 'Dutch',
        'nl_BE' => 'waba.lang_codes.nl_BE', // 'Dutch (Belgium)',
        'en' => 'waba.lang_codes.en', // 'English',
        'en_GB' => 'waba.lang_codes.en_GB', // 'English (United Kingdom)',
        'en_US' => 'waba.lang_codes.en_US', // 'English (United States)',
        'en_AE' => 'waba.lang_codes.en_AE', // 'English (United Arab Emirates)',
        'en_AU' => 'waba.lang_codes.en_AU', // 'English (Australia)',
        'en_CA' => 'waba.lang_codes.en_CA', // 'English (Canada)',
        'en_GH' => 'waba.lang_codes.en_GH', // 'English (Ghana)',
        'en_IE' => 'waba.lang_codes.en_IE', // 'English (Ireland)',
        'en_IN' => 'waba.lang_codes.en_IN', // 'English (India)',
        'en_JM' => 'waba.lang_codes.en_JM', // 'English (Jamaica)',
        'en_MY' => 'waba.lang_codes.en_MY', // 'English (Malaysia)',
        'en_NZ' => 'waba.lang_codes.en_NZ', // 'English (New Zealand)',
        'en_QA' => 'waba.lang_codes.en_QA', // 'English (Qatar)',
        'en_SG' => 'waba.lang_codes.en_SG', // 'English (Singapore)',
        'en_UG' => 'waba.lang_codes.en_UG', // 'English (Uganda)',
        'en_ZA' => 'waba.lang_codes.en_ZA', // 'English (South Africa)',
        'et' => 'waba.lang_codes.et', // 'Estonian',
        'fil' => 'waba.lang_codes.fil', // 'Filipino',
        'fi' => 'waba.lang_codes.fi', // 'Finnish',
        'fr' => 'waba.lang_codes.fr', // 'French',
        'fr_BE' => 'waba.lang_codes.fr_BE', // 'French (Belgium)',
        'fr_CA' => 'waba.lang_codes.fr_CA', // 'French (Canada)',
        'fr_CH' => 'waba.lang_codes.fr_CH', // 'French (Switzerland)',
        'fr_CI' => 'waba.lang_codes.fr_CI', // 'French (Ivory Coast)',
        'fr_MA' => 'waba.lang_codes.fr_MA', // 'French (Morocco)',
        'ka' => 'waba.lang_codes.ka', // 'Georgian',
        'de' => 'waba.lang_codes.de', // 'German',
        'de_AT' => 'waba.lang_codes.de_AT', // 'German (Austria)',
        'de_CH' => 'waba.lang_codes.de_CH', // 'German (Switzerland)',
        'el' => 'waba.lang_codes.el', // 'Greek',
        'gu' => 'waba.lang_codes.gu', // 'Gujarati',
        'ha' => 'waba.lang_codes.ha', // 'Hausa',
        'he' => 'waba.lang_codes.he', // 'Hebrew',
        'hi' => 'waba.lang_codes.hi', // 'Hindi',
        'hu' => 'waba.lang_codes.hu', // 'Hungarian',
        'id' => 'waba.lang_codes.id', // 'Indonesian',
        'ga' => 'waba.lang_codes.ga', // 'Irish',
        'it' => 'waba.lang_codes.it', // 'Italian',
        'ja' => 'waba.lang_codes.ja', // 'Japanese',
        'kn' => 'waba.lang_codes.kn', // 'Kannada',
        'kk' => 'waba.lang_codes.kk', // 'Kazakh',
        'rw_RW' => 'waba.lang_codes.rw_RW', // 'Kinyarwanda',
        'ko' => 'waba.lang_codes.ko', // 'Korean',
        'ky_KG' => 'waba.lang_codes.ky_KG', // 'Kyrgyz (Kyrgyzstan)',
        'lo' => 'waba.lang_codes.lo', // 'Lao',
        'lv' => 'waba.lang_codes.lv', // 'Latvian',
        'lt' => 'waba.lang_codes.lt', // 'Lithuanian',
        'mk' => 'waba.lang_codes.mk', // 'Macedonian',
        'ms' => 'waba.lang_codes.ms', // 'Malay',
        'ml' => 'waba.lang_codes.ml', // 'Malayalam',
        'mr' => 'waba.lang_codes.mr', // 'Marathi',
        'nb' => 'waba.lang_codes.nb', // 'Norwegian',
        'ps_AF' => 'waba.lang_codes.ps_AF', // 'Pashto',
        'fa' => 'waba.lang_codes.fa', // 'Persian',
        'pl' => 'waba.lang_codes.pl', // 'Polish',
        'pt_BR' => 'waba.lang_codes.pt_BR', // 'Portuguese (Brazil)',
        'pt_PT' => 'waba.lang_codes.pt_PT', // 'Portuguese (Portugal)',
        'pa' => 'waba.lang_codes.pa', // 'Punjabi',
        'ro' => 'waba.lang_codes.ro', // 'Romanian',
        'ru' => 'waba.lang_codes.ru', // 'Russian',
        'sr' => 'waba.lang_codes.sr', // 'Serbian',
        'si_LK' => 'waba.lang_codes.si_LK', // 'Sinhala',
        'sk' => 'waba.lang_codes.sk', // 'Slovak',
        'sl' => 'waba.lang_codes.sl', // 'Slovenian',
        'es' => 'waba.lang_codes.es', // 'Spanish',
        'es_AR' => 'waba.lang_codes.es_AR', // 'Spanish (Argentina)',
        'es_CL' => 'waba.lang_codes.es_CL', // 'Spanish (Chile)',
        'es_CO' => 'waba.lang_codes.es_CO', // 'Spanish (Colombia)',
        'es_CR' => 'waba.lang_codes.es_CR', // 'Spanish (Costa Rica)',
        'es_DO' => 'waba.lang_codes.es_DO', // 'Spanish (Dominican Republic)',
        'es_EC' => 'waba.lang_codes.es_EC', // 'Spanish (Ecuador)',
        'es_HN' => 'waba.lang_codes.es_HN', // 'Spanish (Honduras)',
        'es_MX' => 'waba.lang_codes.es_MX', // 'Spanish (Mexico)',
        'es_PA' => 'waba.lang_codes.es_PA', // 'Spanish (Panama)',
        'es_PE' => 'waba.lang_codes.es_PE', // 'Spanish (Peru)',
        'es_ES' => 'waba.lang_codes.es_ES', // 'Spanish (Spain)',
        'es_UY' => 'waba.lang_codes.es_UY', // 'Spanish (Uruguay)',
        'sw' => 'waba.lang_codes.sw', // 'Swahili',
        'sv' => 'waba.lang_codes.sv', // 'Swedish',
        'ta' => 'waba.lang_codes.ta', // 'Tamil',
        'te' => 'waba.lang_codes.te', // 'Telugu',
        'th' => 'waba.lang_codes.th', // 'Thai',
        'tr' => 'waba.lang_codes.tr', // 'Turkish',
        'uk' => 'waba.lang_codes.uk', // 'Ukrainian',
        'ur' => 'waba.lang_codes.ur', // 'Urdu',
        'uz' => 'waba.lang_codes.uz', // 'Uzbek',
        'vi' => 'waba.lang_codes.vi', // 'Vietnamese',
        'zu' => 'waba.lang_codes.zu', // 'Zulu',
    ],

    'enabled_languages' => [
        'es',       // Spanish
        'es_AR',    // Spanish (Argentina)
        'es_MX',    // Spanish (Mexico)
        'en',       // English
        'en_US',    // English (United States)
        'pt_BR',    // Portuguese (Brazil)
    ],
];
